image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REGISTRY_URL: "registry.gitlab.com/vlad15lav/ai-coocking-assistant"

cache:
  key:
    files:
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .cache/pip
    - env/

# .create_environment:
#   before_script:
#     - python --version
#     - python -m venv ./env
#     - ./env/Scripts/activate

stages:
  - linter


# Continuous Integration
linter_job:
  # extends: .create_environment
  stage: linter
  rules:
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      changes:
        - /*.py
  script:
    - echo "Starting linters..."
    - pip install flake8
    - flake8 src
